import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }: { data: any }) {
    console.log(data, ' data');
    return (
        <>
            <Head>
                <title>Extract String from PDF</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>{data}</main>
        </>
    );
}

export async function getStaticProps() {
    const res = await fetch('http://localhost:3000/api/read-pdf');
    const { data } = await res.json();

    return {
        props: {
            data,
        },
    };
}
